/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as InstitutionRouteImport } from './routes/institution'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as StudentRouteImport } from './routes/student'
import { Route as InstitutionIndexRouteImport } from './routes/institution.index'
import { Route as InstitutionProfileRouteImport } from './routes/institution.profile'
import { Route as InstitutionStudentsRouteImport } from './routes/institution.students'
import { Route as OrganizationIndexRouteImport } from './routes/organization.index'
import { Route as OrganizationApplicantsRouteImport } from './routes/organization.applicants'
import { Route as OrganizationPostRouteImport } from './routes/organization.post'
import { Route as OrganizationProfileRouteImport } from './routes/organization.profile'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentInternshipsRouteImport } from './routes/student.internships'
import { Route as StudentLearningRouteImport } from './routes/student.learning'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentAssessmentInternshipIdRouteImport } from './routes/student.assessment.$internshipId'
import { Route as StudentInternshipsIndexRouteImport } from './routes/student.internships.index'
import { Route as StudentInternshipsInternshipIdRouteImport } from './routes/student.internships.$internshipId'
import { Route as StudentReportInternshipIdRouteImport } from './routes/student.report.$internshipId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionRoute = InstitutionRouteImport.update({
  id: '/institution',
  path: '/institution',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionIndexRoute = InstitutionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionProfileRoute = InstitutionProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionStudentsRoute = InstitutionStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => InstitutionRoute,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationApplicantsRoute = OrganizationApplicantsRouteImport.update({
  id: '/applicants',
  path: '/applicants',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationPostRoute = OrganizationPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationProfileRoute = OrganizationProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => OrganizationRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentInternshipsRoute = StudentInternshipsRouteImport.update({
  id: '/internships',
  path: '/internships',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLearningRoute = StudentLearningRouteImport.update({
  id: '/learning',
  path: '/learning',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAssessmentInternshipIdRoute =
  StudentAssessmentInternshipIdRouteImport.update({
    id: '/assessment/$internshipId',
    path: '/assessment/$internshipId',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentInternshipsIndexRoute = StudentInternshipsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentInternshipsRoute,
} as any)
const StudentInternshipsInternshipIdRoute =
  StudentInternshipsInternshipIdRouteImport.update({
    id: '/$internshipId',
    path: '/$internshipId',
    getParentRoute: () => StudentInternshipsRoute,
  } as any)
const StudentReportInternshipIdRoute =
  StudentReportInternshipIdRouteImport.update({
    id: '/report/$internshipId',
    path: '/report/$internshipId',
    getParentRoute: () => StudentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/institution': typeof InstitutionRouteWithChildren
  '/organization': typeof OrganizationRouteWithChildren
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/institution/profile': typeof InstitutionProfileRoute
  '/institution/students': typeof InstitutionStudentsRoute
  '/organization/applicants': typeof OrganizationApplicantsRoute
  '/organization/post': typeof OrganizationPostRoute
  '/organization/profile': typeof OrganizationProfileRoute
  '/student/internships': typeof StudentInternshipsRouteWithChildren
  '/student/learning': typeof StudentLearningRoute
  '/student/profile': typeof StudentProfileRoute
  '/institution/': typeof InstitutionIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/assessment/$internshipId': typeof StudentAssessmentInternshipIdRoute
  '/student/internships/$internshipId': typeof StudentInternshipsInternshipIdRoute
  '/student/report/$internshipId': typeof StudentReportInternshipIdRoute
  '/student/internships/': typeof StudentInternshipsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/register': typeof RegisterRoute
  '/institution/profile': typeof InstitutionProfileRoute
  '/institution/students': typeof InstitutionStudentsRoute
  '/organization/applicants': typeof OrganizationApplicantsRoute
  '/organization/post': typeof OrganizationPostRoute
  '/organization/profile': typeof OrganizationProfileRoute
  '/student/learning': typeof StudentLearningRoute
  '/student/profile': typeof StudentProfileRoute
  '/institution': typeof InstitutionIndexRoute
  '/organization': typeof OrganizationIndexRoute
  '/student': typeof StudentIndexRoute
  '/student/assessment/$internshipId': typeof StudentAssessmentInternshipIdRoute
  '/student/internships/$internshipId': typeof StudentInternshipsInternshipIdRoute
  '/student/report/$internshipId': typeof StudentReportInternshipIdRoute
  '/student/internships': typeof StudentInternshipsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/institution': typeof InstitutionRouteWithChildren
  '/organization': typeof OrganizationRouteWithChildren
  '/register': typeof RegisterRoute
  '/student': typeof StudentRouteWithChildren
  '/institution/profile': typeof InstitutionProfileRoute
  '/institution/students': typeof InstitutionStudentsRoute
  '/organization/applicants': typeof OrganizationApplicantsRoute
  '/organization/post': typeof OrganizationPostRoute
  '/organization/profile': typeof OrganizationProfileRoute
  '/student/internships': typeof StudentInternshipsRouteWithChildren
  '/student/learning': typeof StudentLearningRoute
  '/student/profile': typeof StudentProfileRoute
  '/institution/': typeof InstitutionIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/assessment/$internshipId': typeof StudentAssessmentInternshipIdRoute
  '/student/internships/$internshipId': typeof StudentInternshipsInternshipIdRoute
  '/student/report/$internshipId': typeof StudentReportInternshipIdRoute
  '/student/internships/': typeof StudentInternshipsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/institution'
    | '/organization'
    | '/register'
    | '/student'
    | '/institution/profile'
    | '/institution/students'
    | '/organization/applicants'
    | '/organization/post'
    | '/organization/profile'
    | '/student/internships'
    | '/student/learning'
    | '/student/profile'
    | '/institution/'
    | '/organization/'
    | '/student/'
    | '/student/assessment/$internshipId'
    | '/student/internships/$internshipId'
    | '/student/report/$internshipId'
    | '/student/internships/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/register'
    | '/institution/profile'
    | '/institution/students'
    | '/organization/applicants'
    | '/organization/post'
    | '/organization/profile'
    | '/student/learning'
    | '/student/profile'
    | '/institution'
    | '/organization'
    | '/student'
    | '/student/assessment/$internshipId'
    | '/student/internships/$internshipId'
    | '/student/report/$internshipId'
    | '/student/internships'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/institution'
    | '/organization'
    | '/register'
    | '/student'
    | '/institution/profile'
    | '/institution/students'
    | '/organization/applicants'
    | '/organization/post'
    | '/organization/profile'
    | '/student/internships'
    | '/student/learning'
    | '/student/profile'
    | '/institution/'
    | '/organization/'
    | '/student/'
    | '/student/assessment/$internshipId'
    | '/student/internships/$internshipId'
    | '/student/report/$internshipId'
    | '/student/internships/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  InstitutionRoute: typeof InstitutionRouteWithChildren
  OrganizationRoute: typeof OrganizationRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution': {
      id: '/institution'
      path: '/institution'
      fullPath: '/institution'
      preLoaderRoute: typeof InstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution/': {
      id: '/institution/'
      path: '/'
      fullPath: '/institution/'
      preLoaderRoute: typeof InstitutionIndexRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/profile': {
      id: '/institution/profile'
      path: '/profile'
      fullPath: '/institution/profile'
      preLoaderRoute: typeof InstitutionProfileRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/students': {
      id: '/institution/students'
      path: '/students'
      fullPath: '/institution/students'
      preLoaderRoute: typeof InstitutionStudentsRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/organization/': {
      id: '/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/applicants': {
      id: '/organization/applicants'
      path: '/applicants'
      fullPath: '/organization/applicants'
      preLoaderRoute: typeof OrganizationApplicantsRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/post': {
      id: '/organization/post'
      path: '/post'
      fullPath: '/organization/post'
      preLoaderRoute: typeof OrganizationPostRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/profile': {
      id: '/organization/profile'
      path: '/profile'
      fullPath: '/organization/profile'
      preLoaderRoute: typeof OrganizationProfileRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/internships': {
      id: '/student/internships'
      path: '/internships'
      fullPath: '/student/internships'
      preLoaderRoute: typeof StudentInternshipsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/learning': {
      id: '/student/learning'
      path: '/learning'
      fullPath: '/student/learning'
      preLoaderRoute: typeof StudentLearningRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/assessment/$internshipId': {
      id: '/student/assessment/$internshipId'
      path: '/assessment/$internshipId'
      fullPath: '/student/assessment/$internshipId'
      preLoaderRoute: typeof StudentAssessmentInternshipIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/internships/': {
      id: '/student/internships/'
      path: '/'
      fullPath: '/student/internships/'
      preLoaderRoute: typeof StudentInternshipsIndexRouteImport
      parentRoute: typeof StudentInternshipsRoute
    }
    '/student/internships/$internshipId': {
      id: '/student/internships/$internshipId'
      path: '/$internshipId'
      fullPath: '/student/internships/$internshipId'
      preLoaderRoute: typeof StudentInternshipsInternshipIdRouteImport
      parentRoute: typeof StudentInternshipsRoute
    }
    '/student/report/$internshipId': {
      id: '/student/report/$internshipId'
      path: '/report/$internshipId'
      fullPath: '/student/report/$internshipId'
      preLoaderRoute: typeof StudentReportInternshipIdRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface InstitutionRouteChildren {
  InstitutionProfileRoute: typeof InstitutionProfileRoute
  InstitutionStudentsRoute: typeof InstitutionStudentsRoute
  InstitutionIndexRoute: typeof InstitutionIndexRoute
}

const InstitutionRouteChildren: InstitutionRouteChildren = {
  InstitutionProfileRoute: InstitutionProfileRoute,
  InstitutionStudentsRoute: InstitutionStudentsRoute,
  InstitutionIndexRoute: InstitutionIndexRoute,
}

const InstitutionRouteWithChildren = InstitutionRoute._addFileChildren(
  InstitutionRouteChildren,
)

interface OrganizationRouteChildren {
  OrganizationApplicantsRoute: typeof OrganizationApplicantsRoute
  OrganizationPostRoute: typeof OrganizationPostRoute
  OrganizationProfileRoute: typeof OrganizationProfileRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
}

const OrganizationRouteChildren: OrganizationRouteChildren = {
  OrganizationApplicantsRoute: OrganizationApplicantsRoute,
  OrganizationPostRoute: OrganizationPostRoute,
  OrganizationProfileRoute: OrganizationProfileRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
}

const OrganizationRouteWithChildren = OrganizationRoute._addFileChildren(
  OrganizationRouteChildren,
)

interface StudentInternshipsRouteChildren {
  StudentInternshipsInternshipIdRoute: typeof StudentInternshipsInternshipIdRoute
  StudentInternshipsIndexRoute: typeof StudentInternshipsIndexRoute
}

const StudentInternshipsRouteChildren: StudentInternshipsRouteChildren = {
  StudentInternshipsInternshipIdRoute: StudentInternshipsInternshipIdRoute,
  StudentInternshipsIndexRoute: StudentInternshipsIndexRoute,
}

const StudentInternshipsRouteWithChildren =
  StudentInternshipsRoute._addFileChildren(StudentInternshipsRouteChildren)

interface StudentRouteChildren {
  StudentInternshipsRoute: typeof StudentInternshipsRouteWithChildren
  StudentLearningRoute: typeof StudentLearningRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentAssessmentInternshipIdRoute: typeof StudentAssessmentInternshipIdRoute
  StudentReportInternshipIdRoute: typeof StudentReportInternshipIdRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentInternshipsRoute: StudentInternshipsRouteWithChildren,
  StudentLearningRoute: StudentLearningRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentAssessmentInternshipIdRoute: StudentAssessmentInternshipIdRoute,
  StudentReportInternshipIdRoute: StudentReportInternshipIdRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  InstitutionRoute: InstitutionRouteWithChildren,
  OrganizationRoute: OrganizationRouteWithChildren,
  RegisterRoute: RegisterRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
